Repository kanghanju/team9, pull requests merged in 2024-03, with the labels that each got.

#6 feat/#4 로그인회원가입 화면구현
  src/main/resources/static/css/user/login.css
  src/main/resources/static/css/user/signup.css
  src/main/resources/static/js/user/login.js
  src/main/resources/static/js/user/signup.js
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/signup.html
Labels: 🌸frontend

#10 feat/#1 엔티티 구성
  src/main/java/com/example/team9/Team9Application.java
  src/main/java/com/example/team9/board/domain/Board.java
  src/main/java/com/example/team9/comment/controller/CommentController.java
  src/main/java/com/example/team9/comment/domain/Comment.java
  src/main/java/com/example/team9/commentlike/domain/CommentLike.java
  src/main/java/com/example/team9/grade/domain/Grade.java
  src/main/java/com/example/team9/member/domain/Member.java
  src/main/java/com/example/team9/post/controller/PostController.java
  src/main/java/com/example/team9/post/domain/Post.java
  src/main/java/com/example/team9/postlike/domain/PostLike.java
Labels: 🍀backend

#11 feat/#8 게시글 목록, 작성화면 구현
  src/main/resources/static/css/post/post_create.css
  src/main/resources/static/css/post/post_list.css
  src/main/resources/templates/post/create.html
  src/main/resources/templates/post/post_list.html
Labels: 🌈feature, 🌸frontend

#12 feat/#7 마이페이지화면구현
  src/main/resources/static/css/user/mypage.css
  src/main/resources/static/js/user/mypage.js
  src/main/resources/templates/user/mypage.html
  src/main/resources/templates/user/signup.html
Labels: 🌈feature

#13 feat/#9 운영자페이지 화면구현
  src/main/resources/static/css/admin/admin.css
  src/main/resources/static/css/index.css
  src/main/resources/static/images/search.png
  src/main/resources/static/js/admin/admin.js
  src/main/resources/templates/admin/admin.html
  src/main/resources/templates/index.html
Labels: 🌈feature, 🌸frontend

#17 Feat/#16 엔티티 수정
  src/main/java/com/example/team9/board/domain/Board.java
  src/main/java/com/example/team9/comment/domain/Comment.java
  src/main/java/com/example/team9/commentlike/domain/CommentLike.java
  src/main/java/com/example/team9/grade/domain/Grade.java
  src/main/java/com/example/team9/member/domain/Member.java
  src/main/java/com/example/team9/post/domain/Post.java
Labels: 🍀backend

#19 feat/#15 마이페이지운영자페이지수정
  src/main/resources/static/css/admin/admin.css
  src/main/resources/static/js/admin/admin.js
  src/main/resources/templates/admin/admin.html
  src/main/resources/templates/index.html
Labels: 🌸frontend

#20 feat/#14 게시물상세화면구현
  src/main/resources/static/css/post/post_detail.css
  src/main/resources/templates/post/post_detail.html
Labels: 🌈feature, 🌸frontend
